// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package go_graphql_jobs

import (
	"time"

	"github.com/projects/go-graphql-jobs/models"
)

type Job struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Location    string      `json:"location"`
	CreatedBy   models.User `json:"createdBy"`
	CreatedAt   time.Time   `json:"createdAt"`
	DeletedAt   *time.Time  `json:"deletedAt"`
}

type NewApplication struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	JobID string `json:"jobID"`
	CvURL string `json:"cvURL"`
}

type NewJob struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Location    string `json:"location"`
	CreatedByID string `json:"createdByID"`
}
